### PR TITLE
Swift 3.0 library update

### PR DESCRIPTION
**Pull request by dimakomar**
updated library to swift 3.0 without update of example @teodorpatras

### CODE REVIEW

**Comment by davidrothera** [comment]
Change the Xcode version and the sim version in the `.travis.yml` file to get the tests to run properly:

```yml
# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode8
env:
  global:
    - WORKSPACE=EasyTipView.xcworkspace
    - FRAMEWORK_NAME=EasyTipView
    - PROJECT=EasyTipView.xcodeproj
    - SCHEME=EasyTipView
    - SDK=iphonesimulator10.0
install:
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet
before_deploy:
  - carthage build --no-skip-current
  - carthage archive $FRAMEWORK_NAME
script:
- set -o pipefail
- xcodebuild test -workspace $WORKSPACE -scheme $SCHEME -sdk $SDK ONLY_ACTIVE_ARCH=NO | xcpretty -c
- pod lib lint --quick
```

**Comment by davidrothera** [comment]
`xcode8` not `xcode8.0`

**Comment by dimakomar** [comment]
@davidrothera seem like test are still failing

**Comment by davidrothera** [comment]
Looks like this is to do with the build and run command, in another project (which is working with iOS10) I use:

`xcodebuild -scheme 'FooBar' -project FooBar.xcodeproj -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.0' build test`

**Comment by dimakomar** [comment]
@davidrothera ok, its failing now cause I haven't updated tests for swift 3.0, due to error log, let me do it a bit later

**Comment by teodorpatras** [comment]
Thanks a lot for your help guys!

**Pull request closed without merging**
