### PR TITLE
XCode 10.2 / Swift 5, Added AppStore desired 1024x1024 AppIcon

### PR DESCRIPTION
**Pull request by John-Wolfe-Bose**
Updated for Xcode 10.2, Swift 5

Added 1024x1024 Sample App AppStore AppIcon (quiets compiler warning)

**NOTE: This will fail CI, unless/until you set up your CI to use XCode 10.2**

### CODE REVIEW

**Comment by krachtstefan** [comment]
This looks great. Can we have this please! 🙏

**Comment by John-Wolfe-Bose** [comment]
Absolutely!

John Wolfe
iOS Developer

BOSE
Health Division
Mobile Apps & User Interface

Mobile +1 617 901 2855

**Comment by danielrobleM** [comment]
Hi! , any updates 🙏🙏🙏?

**Comment by John-Wolfe-Bose** [comment]
I think the Travis CI build failed because the code is expecting Xcode 10.2 - and is failing on Xcode 10.1...

**Comment by danielrobleM** [comment]
[Travis](https://github.com/teodorpatras/EasyTipView/blob/master/.travis.yml) is actually using  `osx_image: xcode10` , not sure how to changed to `osx_image: xcode10.2`🤔

**Comment by teodorpatras** [comment]
@John-Wolfe-Bose thank you for submitting this PR! I added it to my todo list and will attend to it in the near future!

**Comment by teodorpatras** [comment]
Unfortunately PR has diverged too much and requires a refactor before merging it. Closed until further notice.

**Pull request closed without merging**
