### PR TITLE
Swift 3.0

### PR DESCRIPTION
**Pull request by warren-gavin**
Updates for the latest Xcode Beta 4 and Swift 3.0 changes

### CODE REVIEW

**Comment by felixLam** [comment]
I have fixed support for Beta 6 in a PR https://github.com/warren-gavin/EasyTipView/pull/1

**Comment by teodorpatras** [comment]
can you modify the`travis.yml` file to make the CI build pass?

**Comment by carobeta** [comment]
Branch has been updated for beta 6?

**Comment by felixLam** [comment]
Hi @teodorpatras I have created a new PR to be able to test travis integration. Will do my best to get this working on #45

**Comment by teodorpatras** [comment]
Thanks a lot for your help!

**Comment by warren-gavin** [comment]
My apologies for not helping out. Lost my job and had a busy month!

**Comment by teodorpatras** [comment]
Don't worry, it's all good ;)

**Pull request closed without merging**
