### PR TITLE
- add preference setting: dismissWhenTouchingOutside

### PR DESCRIPTION
**Pull request by risalba**
- if dismissWhenTouchingOutside==true display put an invisible overlay on the window that would make the tooltip dismiss touching anywhere in the screen

### CODE REVIEW

**Comment by teodorpatras** [comment]
Thanks for the PR and sorry for getting back to you so late! Can you also handle the case where the screen gets rotated?

**Comment by alayers2** [comment]
I tested this today in the simulator, and the screen rotation doesn't mess up the UIView that you tap to dismiss.

**Comment by hernangonzalez** [comment]
This is a nice to have. Any chance of including it?

**Comment by hernangonzalez** [comment]
Actually, code is outdated 😞.

**Comment by mbesnili** [comment]
Can you please merge this ?

**Pull request closed without merging**
