### PR TITLE
Add delegate and change handleTap() logic for handle tap event.

### PR DESCRIPTION
**Pull request by thepinyo**
please merge this for handle tap event.

Now. in use case, i don't need dismiss easyTipView but want to handle tap event for show something.

### CODE REVIEW

**Comment by likeSo** [comment]
Hi, has this pull request merged and released to cocoapods?
I met the same requirements too...
And I didn't find the new delegate method in release 2.0.4...

**Comment by thepinyo** [comment]
@likeso in v2.0.4 not have this feature. Waiting merge this pull request.

**Comment by likeSo** [comment]
@thepinyo It has been 9 days since your contribution, how do you deal with this problem now?
And have you got any response from this repo's owner?
Thanks

**Comment by thepinyo** [comment]
@likeSo i don't have any response from owner. 😂

**Comment by likeSo** [comment]
Seems like the owner is busy now, and his twitter has no updates for years. so now my solution is to add a `easyTipViewDidTap(_)` method in my local pod project...Good luck to you🤣

**Comment by thepinyo** [comment]
ok guy 555

**Comment by thepinyo** [comment]
@teodorpatras @teodorpatras

**Comment by likeSo** [comment]
@thepinyo how about fork this repo and make a new pod?

**Comment by teodorpatras** [comment]
Thanks for your contribution and sorry for the huge delay. Your commit has been integrated here (e4eec79a2a81276bb584e39cca56d435018add2e) and will be available in the next release.

**Pull request closed without merging**
