### PR TITLE
Upgrade to Swift 4

### PR DESCRIPTION
**Pull request by jeffaburt**
After merging this PR, please create a `2.0.0` tag:

```
cd EasyTipView/
git checkout master
git pull origin master
git tag 2.0.0
git push origin 2.0.0
```

Then, send an update to CocoaPods, that way we can just run `pod update EasyTipView` and get all of the Swift 4 goodies:

```
pod trunk push
```

Thanks!

### CODE REVIEW

**Comment by ajayghodadra** [comment]
Is there any plan to merge this PR?

**Comment by jeffaburt** [comment]
+1 😉

**Comment by jeffaburt** [comment]
@teodorpatras can you check this out when you get a free second?

**Comment by jeffaburt** [comment]
Closing because this library now supports Swift 4.1 🎉

**Pull request closed without merging**
